Version 1.7.0

diff --git a/bin/_ldapmodifymachine b/bin/_ldapmodifymachine
--- a/bin/_ldapmodifymachine
+++ b/bin/_ldapmodifymachine
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-#  _ldapdeletemachine : deletes a POSIX machine (user$) account from LDAP
+#  _ldapmodifymachine : modifies a POSIX machine account in LDAP interactively
 
-#  Copyright (C) 2005 Ganaël LAPLANCHE - Linagora
+#  Copyright (C) 2007 Ganaël LAPLANCHE
 #
 #  This program is free software; you can redistribute it and/or
 #  modify it under the terms of the GNU General Public License
@@ -33,6 +33,29 @@ _RUNTIMEFILE="/etc/ldapscripts/runtime"
 _findentry "$MSUFFIX,$SUFFIX" "(&(objectClass=posixAccount)(|(uid=$1)(uidNumber=$1)))"
 [ -z "$_ENTRY" ] && end_die "Machine $1 not found in LDAP (missing ending \$ ?)"
 
-# Delete entry
-_ldapdelete "$_ENTRY" || end_die "Error deleting machine $_ENTRY from LDAP"
-end_ok "Successfully deleted machine $_ENTRY from LDAP"
+# Create temp file
+_TMPFILE=`date "+%Y%m%d-%H%M%S"`
+_TMPFILE=".ldapmodifymachine.$_TMPFILE.$$"
+echo "dn: $_ENTRY" > "$TMPDIR/$_TMPFILE" || end_die "Error creating temporary file $TMPDIR/$_TMPFILE"
+
+# Catch CTRL-C to remove $TMPDIR/$_TMPFILE
+trap 'rm -f "$TMPDIR/$_TMPFILE" ; end_die "Interrupted - Removing temporary file"' 2
+
+# Display entry
+echo "# About to modify the following entry :"
+_ldapsearch "$_ENTRY"
+
+# Edit entry
+echo "# Enter your modifications here, end with CTRL-D."
+echo "dn: $_ENTRY"
+cat >> "$TMPDIR/$_TMPFILE" || end_die "Error writing to temporary file $TMPDIR/$_TMPFILE"
+
+# Send modifications
+cat "$TMPDIR/$_TMPFILE" | _ldapmodify
+if [ $? -ne 0 ]
+then
+  rm -f "$TMPDIR/$_TMPFILE" 2>/dev/null
+  end_die "Error modifying machine entry $_ENTRY in LDAP"
+fi
+rm -f "$TMPDIR/$_TMPFILE" 2>/dev/null
+end_ok "Successfully modified machine entry $_ENTRY in LDAP"
