Version 1.7.1

diff --git a/etc/runtime b/etc/runtime
--- a/etc/runtime
+++ b/etc/runtime
@@ -47,6 +47,13 @@ is_integer () {
   echo "$1" | grep -qE '^[0-9]+$'
 }
 
+# Tests a string (a command name) and tells if it is built-in (true) or external (false)
+# Input : string to test ($1)
+# Output : true or false
+is_builtin () {
+  type "$1" 2>/dev/null | grep -qi 'built'
+}
+
 # Logs a string to $LOGFILE
 # Input : string to log ($1)
 # Output : nothing
@@ -92,27 +99,69 @@ end_die () {
   exit 1
 }
 
+# Allocates and creates a temporary file $_TMPFILE under $TMPDIR
+# Output : nothing
+mktempf () {
+  # Avoid creating two temporary files (must have been released before)
+  [ -n "$_TMPFILE" ] && end_die "Error allocating temporary file $_TMPFILE"
+  # Name temp file
+  _TMPFILE="$TMPDIR/`basename $0`.`date '+%Y%m%d-%H%M%S'`.$$"
+  # Catch CTRL-C to remove $_TMPFILE
+  trap 'rm -f "$_TMPFILE" 2>/dev/null ; end_die "Interrupted - Removing temporary file $_TMPFILE"' 2
+  # Create temp file
+  _TMPMASK=`umask`
+  umask 0077
+  touch "$_TMPFILE" 2>/dev/null || end_die "Error creating temporary file $_TMPFILE"
+  umask "$_TMPMASK"
+}
+
+# Releases a previously allocated temporary file
+# Output : nothing
+reltempf () {
+  # Clean up the temporary file and restore traps
+  rm -f "$_TMPFILE" 2>/dev/null
+  # Reset traps
+  trap -
+  # Clean up name
+  _TMPFILE=''
+}
+
 ### LDAP functions ###
 
 # Performs a search in the LDAP directory
 # Input : base ($1), filter ($2), attribute to display ($3)
 # Output : entry/entries found (stdout)
 _ldapsearch () {
-  $LDAPSEARCHBIN -w "$BINDPWD" -D "$BINDDN" -b "${1:-$SUFFIX}" -xH "$SERVER" -s sub -LLL "${2:-(objectclass=*)}" "${3:-*}" 2>>"$LOGFILE" 
+  if [ -n "$BINDPWDFILE" ]
+  then
+    $LDAPSEARCHBIN -y "$BINDPWDFILE" -D "$BINDDN" -b "${1:-$SUFFIX}" -xH "$SERVER" -s sub -LLL "${2:-(objectclass=*)}" "${3:-*}" 2>>"$LOGFILE" 
+  else
+    $LDAPSEARCHBIN -w "$BINDPWD" -D "$BINDDN" -b "${1:-$SUFFIX}" -xH "$SERVER" -s sub -LLL "${2:-(objectclass=*)}" "${3:-*}" 2>>"$LOGFILE" 
+  fi
 }
 
 # Adds an entry to the LDAP directory
 # Input : LDIF - entry to add (stdin)
 # Output : nothing
 _ldapadd () {
-  $LDAPADDBIN -w "$BINDPWD" -D "$BINDDN" -xH "$SERVER" 2>>"$LOGFILE" 1>/dev/null
+  if [ -n "$BINDPWDFILE" ]
+  then
+    $LDAPADDBIN -y "$BINDPWDFILE" -D "$BINDDN" -xH "$SERVER" 2>>"$LOGFILE" 1>/dev/null
+  else
+    $LDAPADDBIN -w "$BINDPWD" -D "$BINDDN" -xH "$SERVER" 2>>"$LOGFILE" 1>/dev/null
+  fi
 }
 
 # Modifies an entry in the LDAP directory
 # Input : LDIF - modification information (stdin)
 # Output : nothing
 _ldapmodify () {
-  $LDAPMODIFYBIN -w "$BINDPWD" -D "$BINDDN" -xH "$SERVER" 2>>"$LOGFILE" 1>/dev/null
+  if [ -n "$BINDPWDFILE" ]
+  then
+    $LDAPMODIFYBIN -y "$BINDPWDFILE" -D "$BINDDN" -xH "$SERVER" 2>>"$LOGFILE" 1>/dev/null
+  else
+    $LDAPMODIFYBIN -w "$BINDPWD" -D "$BINDDN" -xH "$SERVER" 2>>"$LOGFILE" 1>/dev/null
+  fi
 }
 
 # Renames an entry in the LDAP directory
@@ -123,7 +172,12 @@ _ldaprename () {
   then
     end_die "_ldaprename : missing argument(s)"
   else
-    $LDAPMODRDNBIN -w "$BINDPWD" -D "$BINDDN" -xH "$SERVER" -r "$1" "$2" 2>>"$LOGFILE" 1>/dev/null
+    if [ -n "$BINDPWDFILE" ]
+    then
+      $LDAPMODRDNBIN -y "$BINDPWDFILE" -D "$BINDDN" -xH "$SERVER" -r "$1" "$2" 2>>"$LOGFILE" 1>/dev/null
+    else
+      $LDAPMODRDNBIN -w "$BINDPWD" -D "$BINDDN" -xH "$SERVER" -r "$1" "$2" 2>>"$LOGFILE" 1>/dev/null
+    fi
   fi
 }
 
@@ -132,7 +186,12 @@ _ldaprename () {
 # Output : nothing
 _ldapdelete () {
   [ -z "$1" ] && end_die "_ldapdelete : missing argument"
-  $LDAPDELETEBIN -w "$BINDPWD" -D "$BINDDN" -xH "$SERVER" -r "$1" 2>>"$LOGFILE" 1>/dev/null
+  if [ -n "$BINDPWDFILE" ]
+  then
+    $LDAPDELETEBIN -y "$BINDPWDFILE" -D "$BINDDN" -xH "$SERVER" -r "$1" 2>>"$LOGFILE" 1>/dev/null
+  else
+    $LDAPDELETEBIN -w "$BINDPWD" -D "$BINDDN" -xH "$SERVER" -r "$1" 2>>"$LOGFILE" 1>/dev/null
+  fi
 }
 
 # Extracts LDIF information from $0 (the current script itself)
@@ -140,12 +199,12 @@ _ldapdelete () {
 # Input : depth ($1)
 # Output : extracted LDIF data (stdout)
 _extractldif () {
-  if [ -z "$1" ] || ! is_integer "$1"
+  if [ -n "$1" ] && is_integer "$1"
   then
+    _EXTRACTDEPTH="$1"
+  else
     echo_log "Warning : invalid depth supplied to _extractldif(), using default (2)..."
     _EXTRACTDEPTH='2'
-  else
-    _EXTRACTDEPTH="$1"
   fi
   grep -E "^#{$_EXTRACTDEPTH}[^#]*$" "$0" | sed -e 's|^#*||' 2>>"$LOGFILE"
 }
@@ -154,11 +213,33 @@ _extractldif () {
 # Input : Data to filter (stdin)
 # Output : Filtered data (stdout)
 _filterldif () {
-  sed -e "s|<group>|$_GROUP|g" -e "s|<user>|$_USER|g" -e "s|<uid>|$_UID|g" -e "s|<gid>|$_GID|g" \
-      -e "s|<suffix>|$SUFFIX|g" -e "s|<_suffix>|$_SUFFIX|g" -e "s|<usuffix>|$USUFFIX|g" -e "s|<_usuffix>|$_USUFFIX|g" \
-      -e "s|<msuffix>|$MSUFFIX|g" -e "s|<_msuffix>|$_MSUFFIX|g" -e "s|<gsuffix>|$GSUFFIX|g" -e "s|<_gsuffix>|$_GSUFFIX|g" \
-      -e "s|<home>|$_HOMEDIR|g"  -e "s|<shell>|$USHELL|g" -e "s|<password>|$_PASSWORD|g" -e "s|<gecos>|$_GECOS|g" \
-      -e "s|<entry>|$_ENTRY|g" 2>>"$LOGFILE"
+  # Allocate and create temp file
+  mktempf
+
+  # Generate filter file
+  echo "s|<group>|$_GROUP|g" > "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<user>|$_USER|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<uid>|$_UID|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<gid>|$_GID|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<suffix>|$SUFFIX|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<_suffix>|$_SUFFIX|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<usuffix>|$USUFFIX|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<_usuffix>|$_USUFFIX|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<msuffix>|$MSUFFIX|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<_msuffix>|$_MSUFFIX|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<gsuffix>|$GSUFFIX|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<_gsuffix>|$_GSUFFIX|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<home>|$_HOMEDIR|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<shell>|$USHELL|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<password>|$_PASSWORD|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<gecos>|$_GECOS|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+  echo "s|<entry>|$_ENTRY|g" >> "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+
+  # Use it
+  sed -f "$_TMPFILE" 2>>"$LOGFILE"
+
+  # Release temp file
+  reltempf
 }
 
 ### Nsswitch functions
@@ -273,7 +354,7 @@ _genpassword () {
 }
 
 # Changes a password for a particular DN
-# Input : the new password ($1), the user DN ($2)
+# Input : new clear-text password ($1), user DN ($2)
 # Output : nothing
 _changepassword () {
   if [ -z "$1" ] || [ -z "$2" ]
@@ -284,7 +365,21 @@ _changepassword () {
     then
       echo "$2 : $1" >> "$PASSWORDFILE"
     fi
-    $LDAPPASSWDBIN -w "$BINDPWD" -D "$BINDDN" -xH "$SERVER" -s "$1" "$2" 2>>"$LOGFILE" 1>/dev/null
+    if [ -n "$BINDPWDFILE" ]
+    then
+      ## Change password in a secure way
+      # Allocate and create temp file
+      mktempf
+      # Generate password file
+      echo "$1" > "$_TMPFILE" || end_die "Error writing to temporary file $_TMPFILE"
+      # Change password
+      $LDAPPASSWDBIN -y "$BINDPWDFILE" -D "$BINDDN" -xH "$SERVER" -T "$_TMPFILE" "$2" 2>>"$LOGFILE" 1>/dev/null
+      # Release temp file
+      reltempf
+    else
+      ## Change password in the unsecure, old-fashioned way
+      $LDAPPASSWDBIN -w "$BINDPWD" -D "$BINDDN" -xH "$SERVER" -s "$1" "$2" 2>>"$LOGFILE" 1>/dev/null
+    fi
   fi
 }
 
@@ -301,9 +396,31 @@ then
   end_die "You must have OpenLDAP client commands installed before running these scripts"
 fi
 
-# Check if a full URI has been given
-if ! is_uri "$SERVER"
+# Check for bindpwd file
+if [ ! -f "$BINDPWDFILE" ] || [ ! -r "$BINDPWDFILE" ]
 then
+  if [ -n "$BINDPWD" ]
+  then
+    echo_log "Warning : using command-line passwords, ldapscripts may not be safe"
+  else
+    end_die "Unable to read password file $BINDPWDFILE, exiting..."
+  fi
+fi
+
+# Does the shell has built-in echo command ?
+# If not, print a warning message
+if is_builtin "echo" && is_builtin "["
+then
+  :
+else
+  echo_log "Warning : 'echo' or '[' (test) is not built-in, ldapscripts may not be safe"
+fi
+
+# Check if a full URI has been given
+if is_uri "$SERVER"
+then
+  :
+else
   SERVER="ldap://$SERVER"
 fi
 
